# Generated by Django 4.2.5 on 2023-09-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_id'),
        ('items_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
