# Generated by Django 4.2.5 on 2023-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_listing', '0002_alter_itemlisting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
